data_sources:
  - name: "nvd"
  - name: "vulners"
    api_key: "L884A3520PWGV71JAVXPLQ08AMUUTUVFLABVJQWD1QT5L5SU3481ZEXSHGJECOE5"
  - name: "cisa"
  - name: "circl"

normalizers:
  - basic

exporters:
  - csv
  - json

models_to_evaluate:
  - HUGGINGFACE_API_KEY: ""
  - model: "gpt-4.1-mini"
    type: "api"
    provider: "openai40mini"
    api_key: "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"
    site: "https://api.openai.com/v1"
  - model: "meta-llama/llama-4-scout-17b-16e-instruct"
    type: "api"
    provider: "llama4"
    api_key: "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"
    site: "https://api.groq.com/openai/v1"
  - model: "gemini-2.0-flash"
    type: "api"
    provider: "gemini2flash"
    api_key: "AIzaSyAyxBhAUONlod6klL0DQdGGL55Jnf8IpmU"
    site: "https://generativelanguage.googleapis.com/v1beta/openai/"
