data_sources:
  - name: "nvd"
  - name: "vulners"
    api_key: "L884A3520PWGV71JAVXPLQ08AMUUTUVFLABVJQWD1QT5L5SU3481ZEXSHGJECOE5"
  - name: "cisa"
  - name: "circl"

normalizers:
  - basic

exporters:
  - csv
  - json

models_to_evaluate:
  - HUGGINGFACE_API_KEY: ""
  - model: "gpt-4.1-mini"
    type: "api"
    provider: "openai40mini"
    api_key: "OPENAI_API_KEY"
    site: "https://api.openai.com/v1"
  - model: "meta-llama/llama-4-scout-17b-16e-instruct"
    type: "api"
    provider: "llama4"
    api_key: "LLAMA4_API_KEY"
    site: "https://api.groq.com/openai/v1"
  - model: "gemini-2.0-flash"
    type: "api"
    provider: "gemini2flash"
    api_key: "GEMINI_API_KEY"
    site: "https://generativelanguage.googleapis.com/v1beta/openai/"
